### ISSUE TITLE
'dot' not recognized on Windows

### ISSUE THREAD

**Issue by LancerLunatic** [raineorshine/solgraph#10]
Hello I love solgraph. I've gotten it to work. 
However, I'm on a windows 10 pc. i have downloaded graphwiz and input the path variable in my system settings. I"m not sure if this changes settings for cmd or powershell(or both) but before and after inputing the PATH variable, Graphwiz still doesn't want to work. Using cmd as administrator i am receiving this error:

C:\Users\apoll_000\Documents\SoftwareDevelopmentFiles\token dot -Tpng MyFirstToken.dot > MyFirstToken.png
Error: MyFirstToken.dot: syntax error in line 1 near ' ■s'

using powershell as admin, i get this error. 

PS C:\Users\apoll_000\Documents\SoftwareDevelopmentFiles\token> dot -Tpng MyFirstToken.dot > MyFirstToken_dot.png
dot : The term 'dot' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dot -Tpng MyFirstToken.dot > MyFirstToken_dot.png
+ ~~~
    + CategoryInfo          : ObjectNotFound: (dot:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Any help be appreciated as this problem has been driving me crazy this weekend! I want to see the graphs i made! :-)

**Comment by jamesi2e** [comment]
For anyone coming across this, there are 2 solutions I found:

1. Use the Command Prompt instead of the Powershell.

2. If for any reason, you can't/don't want to use the Command Prompt:

  - Open the created .dot file using a text editor, copy and paste the contents in a new .dot file.

  - Use -o instead of > in the png creation command.
`dot -Tpng MyFirstToken.dot -o MyFirstToken_dot.png`
